# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiko" do
  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "ab23440773048190c90bf4ffe1d46bbd98ae08996c552c3704dadd56edb4c86f"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
    on_arm do
      sha256 "0a3f2fa1e5d17f3c2cd9ffdbca8ea1fb693fe59920c9ff44757775edd1ac30ec"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
  end

  on_linux do
    on_intel do
      sha256 "24e748127cb1b22c59bbc268777da94122ae35a76dfc265d8d832cb54b19e5b9"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
    on_arm do
      sha256 "a470b483636f7fedcb62a62792be72768a2cd34633935f35d3feb8f7d58421c7"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
  end

  name "kiko"
  desc "Privacy-first web analytics collector"
  homepage "https://github.com/hrodrig/kiko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiko"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiko"]
  end

  # No zap stanza required

end
