# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiko" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "01aa712220b614609440939483d684a7e01cdde384a45c30aa1be500a1f2bd89"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
    on_arm do
      sha256 "51a93a3e3ab62280703140457175bc143c89f9a3a408fdfa56fb9a303392d13e"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b09cf6168b2f2b1148ef52f4e21cd6126ad98dcc74a917b2e2e54fdd0e26f98e"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
    on_arm do
      sha256 "402f226e3a9b7ce0051ccb1e963703409023fd22aeffca4dbe961ddd53da7459"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
  end

  name "kiko"
  desc "Privacy-first web analytics collector"
  homepage "https://github.com/hrodrig/kiko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiko"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiko"]
  end

  # No zap stanza required

end
