# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiko" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "c60e122f0d8c35928d15054012b96f86fb84b67cb796217cdc792d8d45934a0b"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
    on_arm do
      sha256 "5d0e01f925d9088d2c0a43bce06e6dea9abdecd7efc132b3d410cc2c50d72067"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
  end

  on_linux do
    on_intel do
      sha256 "f9f0c69fe65e782076c7928390ce9f949e9a1437c0904fee314d25688cc15af8"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
    on_arm do
      sha256 "efb6160830e4efe5a1e1b51b2109176d2a3246a301fe26ca6f40f25ef3b8cdc9"
      url "https://github.com/hrodrig/kiko/releases/download/v#{version}/kiko_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/kiko/"
    end
  end

  name "kiko"
  desc "Privacy-first web analytics collector"
  homepage "https://github.com/hrodrig/kiko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiko"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiko"]
  end

  # No zap stanza required

end
